"""Friendly id -> name tables for the quest map (``.dat``) semantic view.

These tables drive the *semantic* (human-readable) layer of
:mod:`formats.quest_map` — the byte-exact codec never depends on them, so
an unknown id simply renders as a hex fallback and never breaks a
round-trip. Tables are transcribed from
``docs/quest_editor/REFERENCE_DATA.md``; edit there and re-sync if the
reference changes.

* ``OBJECT_NAMES``    — OBJECT_SETS ``base_type`` -> name (object type ids).
* ``ENEMY_NAMES``     — ENEMY_SETS ``base_type`` -> name (enemy type ids).
* ``NPC_SKIN_NAMES``  — NPC skin / appearance ids (used for NPC placements).

Episode note: object/enemy ids are reused across episodes with different
meanings; these tables carry the Episode 1 (and common) names. The Ep2/Ep4
overloads live in REFERENCE_DATA.md and can be layered on later by the UI.
"""
from __future__ import annotations

from typing import Dict

# ---------------------------------------------------------------------------
# Object type ids (OBJECT_SETS, section type 1)
# ---------------------------------------------------------------------------
OBJECT_NAMES: Dict[int, str] = {
    0: "Player Set 1",
    1: "Particle",
    2: "Teleporter",
    3: "Warp",
    4: "Light Collision",
    5: "Item",
    6: "Env Sound",
    7: "Fog Collision",
    8: "Event Collision",
    9: "Chara Collision",
    10: "Elemental Trap",
    11: "Status Trap",
    12: "Heal Trap",
    13: "Large Elemental Trap",
    14: "Obj Room ID",
    15: "Sensor",
    16: "Unknown Item (16)",
    17: "Lensflare",
    18: "Script Collision",
    19: "Heal Ring",
    20: "Map Collision",
    21: "Script Collision A",
    22: "Item Light",
    23: "Radar Collision",
    24: "Fog Collision SW",
    25: "Boss Teleporter",
    26: "Image Board",
    27: "Area Warp (Ep1)",
    28: "Epilogue",
    32: "Box Detect Object",
    33: "Symbol Chat Object",
    34: "Touch Plate Object",
    35: "Targetable Object",
    36: "Effect Object",
    37: "Count Down Object",
    64: "Menu Activation",
    65: "Telepipe Location",
    66: "BGM Collision",
    67: "Main Ragol Teleporter",
    68: "Lobby Teleporter",
    69: "Principal Warp",
    70: "Shop Door",
    71: "Hunter's Guild Door",
    72: "Teleporter Door",
    73: "Medical Center Door",
    74: "Elevator",
    75: "Easter Egg",
    76: "Valentines Heart",
    77: "Christmas Tree",
    78: "Christmas Wreath",
    79: "Halloween Pumpkin",
    80: "21st Century",
    81: "Dr Robotnic / Sonic / Knux / Tails",
    82: "Welcome Board",
    83: "Firework",
    84: "Lobby Screen Door",
    85: "Main Ragol Teleporter (Battle Next)",
    86: "Lab Teleporter Door",
    87: "Pioneer 2 Invisible Touchplate",
    128: "Forest Door",
    129: "Forest Switch",
    130: "Laser Fence",
    131: "Laser Square Fence",
    132: "Forest Laser Fence Switch",
    133: "Light Rays",
    134: "Blue Butterfly",
    135: "Crashed Probe / Probe",
    136: "Random Type Box 1",
    137: "Forest Weather Station",
    138: "Battery",
    139: "Forest Console 1/2",
    140: "Black Sliding Door",
    141: "Rico Message Pod",
    142: "Energy Barrier",
    143: "Forest Rising Bridge",
    144: "Switch (None Door)",
    145: "Enemy Box (Grey)",
    146: "Fixed Type Box",
    147: "Enemy Box (Brown)",
    149: "Empty Type Box",
    150: "Laser Fence Ex",
    151: "Laser Square Fence Ex",
    192: "Floor Panel 1",
    193: "Caves 4 Button Door",
    194: "Caves Normal Door",
    195: "Caves Smashing Pillar",
    196: "Caves Sign 1",
    197: "Caves Sign 2",
    198: "Caves Sign 3",
    199: "Hexagonal Tank",
    200: "Brown Platform",
    201: "Warning Light Object",
    203: "Rainbow",
    204: "Floating Jellyfish",
    205: "Floating Dragonfly",
    206: "Caves Switch Door",
    207: "Robot Recharge Station",
    208: "Caves Cake Shop",
    209: "Caves Rocks (Small)",
    210: "Caves Rocks (Medium)",
    211: "Caves Rocks (Large)",
    222: "Floor Panel 2",
    256: "Mines Door",
    257: "Floor Panel 3",
    258: "Mines Switch Door",
    259: "Large Cryo-Tube",
    260: "Computer (Calus-like)",
    261: "Green Screen Opening/Closing",
    262: "Floating Robot",
    263: "Floating Blue Light",
    267: "Spark Machine",
    268: "Mines Large Flashing Crate",
    304: "Ruins Seal",
    320: "Ruins Teleporter",
    321: "Ruins Warp (Site to Site)",
    322: "Ruins Switch",
    323: "Floor Panel 4",
}

# ---------------------------------------------------------------------------
# Enemy type ids (ENEMY_SETS, section type 2) — Episode 1 base roster.
# ---------------------------------------------------------------------------
ENEMY_NAMES: Dict[int, str] = {
    0: "Booma",
    1: "Savage Wolf",
    2: "Rag Rappy",
    3: "Monest",
    4: "Hildebear",
    5: "Grass Assassin",
    6: "Poison Lily / Del Lily",
    7: "Nano Dragon",
    8: "Evil Shark",
    9: "Pofuilly Slime",
    10: "Pan Arms",
    11: "Gillchic",
    12: "Garanz",
    13: "Sinow Blue",
    14: "Canadine",
    15: "Canane",
    16: "Dubchic Switch",
    17: "Delsaber",
    18: "Chaos Sorcerer",
    19: "Dark Gunner",
    20: "Dark Gunner (Activator)",
    21: "Chaos Bringer",
    22: "Dark Belra",
    23: "Dimenian",
    24: "Bulclaw",
    25: "Claw",
    40: "Dragon (Ep1 Boss)",
    41: "De Rol Le (Ep1 Boss)",
    42: "Vol Opt Control (Ep1 Boss)",
}

# ---------------------------------------------------------------------------
# NPC skin / appearance ids (NPC placements).
# ---------------------------------------------------------------------------
NPC_SKIN_NAMES: Dict[int, str] = {
    1: "Female Base",
    2: "Female Child",
    3: "Female Dwarf",
    4: "Female Fat",
    5: "Female Macho",
    6: "Female Old",
    7: "Female Tall",
    8: "Male Base",
    9: "Male Child",
    10: "Male Dwarf",
    11: "Male Fat",
    12: "Male Macho",
    13: "Male Old",
    14: "Male Tall",
    25: "Blue Soldier",
    26: "Red Soldier",
    27: "Principal Tyrel",
    28: "Tekker",
    29: "Bank Lady",
    30: "Scientist",
    31: "Nurse",
    32: "Irene",
    33: "Broomop",
    34: "Hunter (Male)",
    36: "Ranger (Male)",
    37: "Racast",
    38: "Racaseal",
    39: "Fomarl",
    40: "Fomewm",
    41: "Fomewearl",
    43: "HUnewearl",
    44: "Cast (Male)",
    45: "RAmar",
    48: "HMN FRC W 01",
    49: "NMN FRC M 01",
    50: "NMN FRC W 01",
    208: "Ep2 NPC D0",
    209: "Directrice (Natasha)",
    210: "Dan",
    211: "Ep2 NPC D3",
    240: "Ep2 Armor Shop",
    241: "Ep2 Item Shop",
    242: "Default Fomar",
    243: "Default Ramarl",
    244: "Leo",
    245: "Pagini",
    246: "Ep2 NPC F6",
    247: "Nol",
    248: "Elly",
    249: "Ep2 NPC F9",
    250: "Ep2 Item Shop",
    251: "Ep2 Weapon Shop",
    252: "Security Guard",
    253: "Ep2 Hunters Guild",
    254: "Ep2 Bank Lady",
    256: "Momoka",
    272: "Astark",
    273: "Satellite Lizard",
    274: "Merissa A",
    275: "Girtablulu",
    276: "Zu",
    277: "Boota",
    278: "Dorphon",
    279: "Goran",
    281: "Saint Million",
}
